### ISSUE TITLE
draw in to Mat

### ISSUE THREAD

**Issue by stephanschulz** [orgicus/p5.js-cv#2]
I would like to use cv.drawContour() or cv.rectangle() to draw in to a Mat. This is to help create custom mast Mats which i will later apply to the capture mat.

Is there a way to have access to those openCV functions directly? I see that for now p5.cv.js does not expose them.

this for example does not work:
```
let white = new cv.Scalar(255, 255, 255, 255);
cv.rectangle(myMatRGB,cv.Point(10,10),cv.Point(200,200),white);
```
thx.

**Comment by stephanschulz** [comment]
Got it. Simple mistake.
```
    let white = new cv.Scalar(255, 255, 255, 255);
    cv.rectangle(myMatRGB,new cv.Point(10,10),new cv.Point(200,200),white);
```

**Comment by orgicus** [comment]
@stephanschulz

Aplogies for the late reply, glad you figured it out.

Also, bare in mind JS types map to OpenCV.js nicely:

`cv.rectangle(myMatRGB, {x: 10, y: 10},{x: 200, y:200}, [255, 255, 255, 255]);`

if you happen to work with `p5.Vector` instance, since they already have `.x` and `.y` properties you could use those as points as well.
